Add z field
ACTCollaboration/zCluster pull request #5
Opened 2020-07-04 22:15 UTC by mckabuza

2020-07-04 22:17 UTC, mckabuza commented
Pull request to add zField to the zCluster code.

2020-07-06 08:31 UTC, mattyowl requested changes
Not tried this review thing before - see if you can see/address the comments. If not, let me know

2020-07-06 08:31 UTC, mattyowl commented on bin/zField
> +    if passbandSet == 'SDSS+Ks':
Instead of this block here, get the names of the bands from PhotoRedshiftEngine.bands.

2020-07-06 08:31 UTC, mattyowl commented on bin/zField
> +                           dMapDict['map'], dMapDict['wcs'])s
Syntax error - you would see this just by trying to run zField -h

2020-07-09 08:06 UTC, mattyowl approved these changes
Thanks for sorting this

2020-07-09 08:07 UTC, merged